title: Utsav Panchal
url: " "
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: UA-69243698-4

footer: yes
footer_url: "https://github.com/ankitsultana/ankitsultana.github.io"
footer_text: "Custom theme by Ankit Sultana."

favicon: true
favicon_location: "images/favicon.png"

sass:
  style: compressed
  sass_dir: _sass

nav:
  - name: "About"
    link: "/"
  - name: "Blog"
    link: "/blog"
  - name: "Timeline"
    link: "/books"
